const aliases={ai:["umela inteligence","chatgpt","vibecoding","copilot","prompt"],anglictina:["anglicky","english"],excel:["tabulky","microsoft excel"],komunikace:["asertivita","zpetna vazba","vyjednavani","prezentace"],leadership:["vedeni","manazer","tym","leadership"],produktivita:["time management","soustredeni","fokus","efektivita"],stres:["psychika","wellbeing","emoce","rovnovaha","klid"],obchod:["prodej","zakaznik","sales"],hr:["nabor","personalistika","lidske zdroje"]};
const normalize=v=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("cs").replace(/[^a-z0-9]+/g," ").trim();
const score=(course,raw)=>{const query=normalize(raw);if(!query)return 1;const title=normalize(course.name),slug=normalize(course.slug),tokens=query.split(" ").filter(Boolean),expanded=new Set(tokens);tokens.forEach(t=>(aliases[t]||[]).forEach(a=>expanded.add(a)));let s=0;if(title===query)s+=160;if(title.startsWith(query))s+=90;if(title.includes(query))s+=70;if(slug.includes(query))s+=25;tokens.forEach(t=>{const words=title.split(" ");if(words.includes(t))s+=28;else if(words.some(w=>w.startsWith(t)))s+=18;else if(title.includes(t))s+=10});[...expanded].filter(t=>!tokens.includes(t)).forEach(t=>{if(title.includes(t))s+=8});if(tokens.every(t=>title.includes(t)))s+=35;if(course.flag==="Novinka")s+=2;return s};
const state={catalog:null,query:"",filter:"Vše",limit:18};
const $=s=>document.querySelector(s), grid=$("#courseGrid"), input=$("#search");
function label(n){return n===1?"výsledek":n>=2&&n<=4?"výsledky":"výsledků"}
function filtered(){if(!state.catalog)return[];return state.catalog.courses.map((course,index)=>({course,index,score:score(course,state.query)})).filter(({course,score:s})=>{if(state.query&&s<=0)return false;if(state.filter==="Novinky")return course.flag==="Novinka";if(state.filter==="Podcasty")return normalize(course.name).includes("podcast");if(state.filter==="Naživo")return normalize(course.name).includes("nazivo");return true}).sort((a,b)=>state.query?b.score-a.score:a.index-b.index).map(x=>x.course)}
function card(course,index){const a=document.createElement("a");a.className="courseCard";a.href=course.url;a.target="_blank";a.rel="noreferrer";const visual=document.createElement("div");visual.className=`courseVisual visual${index%6+1}`;const badge=document.createElement("span");badge.textContent=course.flag||(normalize(course.name).includes("podcast")?"Podcast":"Videokurz");const number=document.createElement("b");number.textContent=String(index+1).padStart(2,"0");const arrow=document.createElement("i");arrow.textContent="↗";arrow.setAttribute("aria-hidden","true");visual.append(badge,number,arrow);const body=document.createElement("div");body.className="courseBody";const name=document.createElement("p");name.textContent=course.name;const link=document.createElement("span");link.textContent="Otevřít kurz na Seduo.cz ↗";body.append(name,link);a.append(visual,body);return a}
function render(){const courses=filtered();$("#mode").textContent=state.query?"Výsledky hledání":"Procházet katalog";$("#heading").textContent=state.query?`Nejlepší shody pro „${state.query}“`:"Aktuální kurzy na Seduo";$("#count").textContent=courses.length;$("#countLabel").textContent=label(courses.length);grid.replaceChildren(...courses.slice(0,state.limit).map(card));$("#empty").hidden=courses.length!==0;grid.hidden=courses.length===0;$("#loadMore").hidden=courses.length<=state.limit;$("#clear").hidden=!state.query;$("#shortcut").hidden=!!state.query}
document.querySelectorAll(".filters button").forEach(button=>button.addEventListener("click",()=>{state.filter=button.textContent;state.limit=18;document.querySelectorAll(".filters button").forEach(b=>b.classList.toggle("active",b===button));render()}));
document.querySelectorAll(".quickRow button").forEach(button=>button.addEventListener("click",()=>{state.query=button.textContent;state.filter="Vše";state.limit=18;input.value=state.query;document.querySelectorAll(".filters button").forEach(b=>b.classList.toggle("active",b.textContent==="Vše"));render();input.focus()}));
input.addEventListener("input",()=>{state.query=input.value;state.limit=18;render()});
$("#clear").addEventListener("click",()=>{state.query="";input.value="";render();input.focus()});
$("#reset").addEventListener("click",()=>{state.query="";state.filter="Vše";input.value="";document.querySelectorAll(".filters button").forEach(b=>b.classList.toggle("active",b.textContent==="Vše"));render()});
$("#loadMore").addEventListener("click",()=>{state.limit+=18;render()});
window.addEventListener("keydown",e=>{if(e.key==="/"&&document.activeElement!==input){e.preventDefault();input.focus()}if(e.key==="Escape"){state.query="";input.value="";render();input.blur()}});
fetch("courses.json").then(r=>r.json()).then(data=>{state.catalog=data;$("#total").textContent=data.total_count;$("#updated").textContent=`Index aktualizován ${new Intl.DateTimeFormat("cs-CZ",{day:"numeric",month:"long",year:"numeric",timeZone:"Europe/Prague"}).format(new Date(data.observed_at))}`;render()}).catch(()=>{$("#updated").textContent="Index se nepodařilo načíst";render()});
